name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    env:
      NODE_ENV: production
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 24
        architecture:
          - x64

    name: (Lint) Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - run: corepack enable
      - uses: pnpm/action-setup@v6.0.9
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          cache: 'pnpm'

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile --prod=false

      - name: Generate Prisma Client
        run: pnpm prepare

      - name: 🔠 Lint project
        run: pnpm lint

  build:
    env:
      NODE_ENV: production
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 24
        architecture:
          - x64

    name: (Build) Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - run: corepack enable
      - uses: pnpm/action-setup@v6.0.9
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          cache: 'pnpm'

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile --prod=false

      - name: Generate Prisma Client
        run: pnpm prepare

      - name: 🛠 Build project
        run: pnpm build
